### ISSUE TITLE
Some diff were not found

### ISSUE THREAD

**Issue by meisterleise** [friebetill/obsidian-file-diff#10]
I made some tests with this plugin.  In some cases not all diffs are found/marked. Example:

---
Dummy text is without content, but contains the success greater flowers of some with sky, which acts strong and colourful happiness. We covet quality and purchasing power that amiably conveys knowledge and strategy. Hello design advances a fair deal in which order thereby results comparable that courage and joy are intermingled at boundless and intelligent.

Version 1.4.16

I am a line in M01
---

---
Dummy text is without content, but contains the success greater flowers of some with sky, which acts strong and colourful happiness. We covet quality and purchasing power that amiably conveys knowledge and strategy. Thoughtful design advances a fair deal in which order thereby results comparable that courage and joy are intermingled at boundless and intelligent.

Ende

Here's a line in M02
---

The last line was not found/marked.

**Comment by friebetill** [comment]
Thanks for the report! I fixed the problem with the new version 1.1.0.
