### ISSUE TITLE
Highlight diverging characters/words in 

### ISSUE THREAD

**Issue by ryanwwest** [friebetill/obsidian-file-diff#7]
`Find sync conflicts and merge` is such an awesome addition, it's incredibly convenient and exactly what I needed (and even deletes the unnecessary file after merging!). However, it would be easier when comparing two very long lines to have a darker highlight that highlights the exact characters in each line that diverge (VS Code does something like this). That way you don't have to read from the beginning of the line on each to eventually find a one-character difference. 

Separately, it would also be nice to click the 'accept all' button even on different lines when one file has extra lines, and the other one doesn't. I'm not actually sure why Syncthing doesn't just merge these itself, but sometimes I have two conflicted files and one just has a few new lines added at the end, but I still have to individually accept each one.

Thanks so much, this is a killer plugin.

**Comment by meisterleise** [comment]
Yeah, highlight every single word/character. I would like that too. :)

<img width="1165" alt="image" src="https://github.com/friebetill/obsidian-file-diff/assets/14863470/10ab16e2-c54a-45bd-9519-a5bc220b3964">

**Comment by friebetill** [comment]
Thanks for the feature request! I added the feature with the new version 1.1.0.
