### ISSUE TITLE
Sometimes it identifies equal blocks as different

### ISSUE THREAD

**Issue by AMGMNPLK** [friebetill/obsidian-file-diff#9]
I don't know why, but sometimes it highlights the same blocks. I took both texts and compared them in other tools because maybe my eyes could fail, but they didn't find other differences.

**Comment by AMGMNPLK** [comment]
![CleanShot 2023-11-04 at 07 09 22@2x](https://github.com/friebetill/obsidian-file-diff/assets/19272675/a9419a46-0e98-4bcb-8777-c89aea9b998c)

String 1:

```
# Heading blocks
The heading becomes the question and everything until the next heading is the answer

 ## Regex
Heading: `^#+ *\* *(.+)\n*((?:\n(?:^[^\n#].{0,2}$|^[^\n#].{3}(?<!<!--)[\w\W]+?(?=\n^#+ |$(?![\r\n]))))+)`

To add heading cards, format your headings like this (you must add a * )
```

String 2
```
# Heading blocks
The heading becomes the question and everything until the next heading is the answer

## Regex
Heading: `^#+ *\* *(.+)\n*((?:\n(?:^[^\n#].{0,2}$|^[^\n#].{3}(?<!<!--)[\w\W]+?(?=\n^#+ |$(?![\r\n]))))+)`

To add heading cards, format your headings like this (you must add a * )
```

**Comment by AMGMNPLK** [comment]
In this case I think it is about the three last points or elipsis. If I paste them it looks the same, but in the clipboard the look different. I can't capture the screenshot for it, but it seems that according to some string systems –UTF or something like that?– they look different, like three dots it is not the same than the elipsis.


![CleanShot 2023-11-04 at 19 18 03@2x](https://github.com/friebetill/obsidian-file-diff/assets/19272675/627f6e41-9e91-46e2-b3f2-729efacb6701)


string 1
```
# No enamorarse de la idea/metodología, plan…
```

string 2
```
# No enamorarse de la idea/metodología, plan...
```

**Comment by friebetill** [comment]
Thanks for the examples! The second example is now better displayed in the new version 1.1.0:
<img width="376" alt="image" src="https://github.com/friebetill/obsidian-file-diff/assets/10923085/da858cdc-c066-439a-a85e-16a11d573341">
